# Fazer tupla com sinonimos de rua
street_synonyms = (
    "rua",
    "avenida",
    "alameda",
    "travessa",
    "praça",
    "largo",
    "viela",
    "estrada",
    "boulevard",
    "passagem",
    "via",
    "rodovia"
)

# Fazer tupla com nomes de cidades brasileiras
city_names = (
    "sao paulo",
    "rio de janeiro",
    "salvador",
    "brasilia",
    "fortaleza",
    "belo horizonte",
    "manaus",
    "curitiba",
    "recife",
    "porto alegre",
    "belem",
    "goiania",
    "guarulhos",
    "campinas",
    "sao luis",
    "natal",
    "teresina",
    "campo grande",
    "sao bernardo do campo",
    "osasco",
    "santo andre",
    "joao pessoa",
    "jaboatao dos guararapes",
    "contagem",
    "sao jose dos campos",
    "santa luzia",
    "duque de caxias",
    "feira de santana",
    "sao jose do rio preto",
    "maringa",
    "anapolis",
    "sao vicente",
    "bauru",
    "betim",
    "blumenau",
    "santos",
    "joinville",
    "uberlandia",
    "aracaju",
    "florianopolis",
    "cuiaba",
    "sorocaba",
    "ribeirao preto",
    "feira de santana",
    "americana",
    "uberaba",
    "cariacica",
    "londrina",
    "niteroi"
)
