# Fazer tupla com sinonimos de rua
street_synonyms = (
    "rua",
    "avenida",
    "alameda",
    "travessa",
    "praça",
    "largo",
    "viela",
    "estrada",
    "boulevard",
    "passagem",
    "via",
    "rodovia"
)

# Fazer tupla com nomes de cidades brasileiras
city_names = (
    "sao paulo",
    "rio de janeiro",
    "salvador",
    "brasilia",
    "fortaleza",
    "belo horizonte",
    "manaus",
    "curitiba",
    "recife",
    "porto alegre",
    "belem",
    "goiania",
    "guarulhos",
    "campinas",
    "sao luis",
    "natal",
    "teresina",
    "campo grande",
    "sao bernardo do campo",
    "osasco",
    "santo andre",
    "joao pessoa",
    "jaboatao dos guararapes",
    "contagem",
    "sao jose dos campos",
    "santa luzia",
    "duque de caxias",
    "feira de santana",
    "sao jose do rio preto",
    "maringa",
    "anapolis",
    "sao vicente",
    "bauru",
    "betim",
    "blumenau",
    "santos",
    "joinville",
    "uberlandia",
    "aracaju",
    "florianopolis",
    "cuiaba",
    "sorocaba",
    "ribeirao preto",
    "feira de santana",
    "americana",
    "uberaba",
    "cariacica",
    "londrina",
    "niteroi"
)

# Fazer tupla com o nome de bairros
neighborhood_names = (
    "xaxim",
    "prado velho",
    "batel",
    "centro",
    "cabral",
    "alto da xv",
    "barreirinha",
    "boqueirão",
    "cajuru",
    "campo comprido",
    "cic",
    "lindoia",
    "merces",
    "portao",
    "santa felicidade",
    "santo inacio",
    "sao braz",
    "tingui",
    "agua verde",
    "ahu",
    "bigorrilho",
    "hauer",
    "jardim social",
    "novos",
    "orleans",
    "vila izabel",
    "vista alegre",
    "sao francisco",
    "atuba",
    "campina do siqueira",
    "santa quiteria",
    "bom retiro",
    "cachoeira",
    "taruma",
    "fanny",
    "tatuquara",
    "taboao",
    "butiatuvinha",
    "guabirotuba",
    "hugo lange",
    "ahú",
    "são lourenço",
    "mossunguê",
    "pilarzinho",
    "são joão",
    "capão da imbuia",
    "sítio cercado",
    "umbará",
    "vila fanny",
    "vila hauer",
    "vila isabel"
)

